apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 192.168.0.104:5000/ecommerce-backend:v1
          imagePullPolicy: Always 
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              value: "owams"
            - name: MYSQL_DB
              value: "ecommerce_db"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecommerce
spec:
  selector:
    app: backend
  # MODIFICADO: Cambia el tipo de Service a NodePort
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Puerto interno del servicio
      targetPort: 8000 # Puerto del contenedor
      # NUEVO: Puerto estático en el nodo para acceder desde el exterior
      nodePort: 30080
