services:
  k3s-master:
    image: rancher/k3s:latest
    container_name: k3s-master
    privileged: true
    ports:
      - "6443:6443"    # Kubernetes API Server
      - "10250:10250"  # Kubelet API
      - "8472:8472"    # Flannel VXLAN
    networks:
      k3s-network:
        ipv4_address: 172.24.0.10
    volumes:
      - ./k3s/master:/var/lib/rancher/k3s/storage
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml
      - ./kubernetes:/kubernetes  # Montar los manifiestos de Kubernetes
      - ./kubeconfig:/kubeconfig   # Para acceder al kubeconfig desde el host
    environment:
      - K3S_TOKEN=${MASTER_TOKEN}
      - K3S_NODE_NAME=k3s-master
      - K3S_KUBECONFIG_OUTPUT=/kubeconfig/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    command: >
      server
      --disable traefik
      --disable servicelb
      --write-kubeconfig-mode 644
      --bind-address=0.0.0.0
      --advertise-address=172.24.0.10
      --node-external-ip=172.24.0.10
      --cluster-init
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kubectl", "get", "nodes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  k3s-worker-1:
    image: rancher/k3s:latest
    container_name: k3s-worker-1
    privileged: true
    ports:
      - "10251:10250"
    networks:
      k3s-network:
        ipv4_address: 172.24.0.11
    volumes:
      - ./k3s/worker-1:/var/lib/rancher/k3s/storage
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml
    environment:
      - K3S_URL=https://172.24.0.10:6443
      - K3S_TOKEN=${MASTER_TOKEN}
      - K3S_NODE_NAME=k3s-worker-1
    command: agent
    restart: unless-stopped
    depends_on:
      k3s-master:
        condition: service_healthy

  k3s-worker-2:
    image: rancher/k3s:latest
    container_name: k3s-worker-2
    privileged: true
    ports:
      - "10252:10250"
    networks:
      k3s-network:
        ipv4_address: 172.24.0.12
    volumes:
      - ./k3s/worker-2:/var/lib/rancher/k3s/storage
      - ./registries.yaml:/etc/rancher/k3s/registries.yaml
    environment:
      - K3S_URL=https://172.24.0.10:6443
      - K3S_TOKEN=${MASTER_TOKEN}
      - K3S_NODE_NAME=k3s-worker-2
    command: agent
    restart: unless-stopped
    depends_on:
      k3s-master:
        condition: service_healthy

networks:
  k3s-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
